[package]
name = "rendezvous"
version = "0.0.1"
authors = ["Adam Gashlin"]

[dependencies]
rand = "0.5"
futures = "0.1"
futures-timer = "0.1"
hyper = "0.12"
url = "1.7"
lazy_static = "1.1"
serde_derive = "1.0"
serde = "1.0"
toml = "0.4"
